export interface Hospital {
  name: string;
  description: string;
  address: string;
  phone: string;
  cost?: string; // 타입이 string인 이유 : 가격이 하나로 정해진게 아니라 ~ 이용해 범위로 정해진 것이 있어서 string으로
  //cost가 없는 경우 '-' 표시
  info?: string; //홈페이지 없는 경우 '없음'
  homepage?: string;
}

export const predefinedHospitals: Hospital[] = [
  {
    name: '(의)성광의료재단 차여성의원',
    description: '(의)성광의료재단 차여성의원병원에 대한 설명란입니다.',
    address: '서울특별시 중구 한강대로 416 2층 (남대문로5가, 서울스퀘어)',
    phone: '02-2002-0300',
    cost: '-',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'https://seoul.chamc.co.kr/default.aspx',
  },
  {
    name: '감자와눈사람여성의원',
    description: '감자와눈사람여성의원에 대한 설명란입니다.',
    address: '서울특별시 강서구 마곡중앙5로 22 웰튼메디플렉스 5층 (마곡동)',
    phone: '02-467-6727',
    cost: '55000',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'https://www.potatosnow.com/',
  },
  {
    name: '강동드림산부인과의원',
    description: '강동드림산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 강동구 상일로12길 97 (강일동)',
    phone: '02-441-4567',
    cost: '60000',
    info: '인공 수정 시술',
    homepage: 'http://www.gangdongdream.com/',
  },
  {
    name: '강북삼성병원',
    description: '강북삼성병원에 대한 설명란입니다.',
    address: '서울특별시 종로구 새문안로 29 (평동)',
    phone: '02-2001-2001',
    cost: '-',
    info: '인공 수정 시술',
    homepage: 'https://www.kbsmc.co.kr/index.jsp?ignore=Y',
  },
  {
    name: '고려대학교의과대학부속구로병원',
    description: '고려대학교의과대학부속구로병원에 대한 설명란입니다.',
    address: '서울특별시 구로구 구로동로 148 고려대부속구로병원 (구로동)',
    phone: '02-2626-1114',
    cost: '-',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'http://guro.kumc.or.kr/main/index.do',
  },
  {
    name: '국립중앙의료원',
    description: '국립중앙의료원에 대한 설명란입니다.',
    address: '서울특별시 중구 을지로 245 (을지로6가)',
    phone: '02-2260-7114',
    cost: '-',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'https://www.nmc.or.kr/nmc/main/main.do',
  },
  {
    name: '김정화산부인과의원',
    description: '김정화산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 관악구 양녕로 46 3층 305호 (봉천동)',
    phone: '02-883-3307',
    cost: '88000',
    info: '인공 수정 시술',
    homepage: '없음',
    //해당 홈페이지 접속 안됨
  },
  {
    name: '노원을지대학교병원',
    description: '노원을지대학교병원에 대한 설명란입니다.',
    address: '서울특별시 노원구 한글비석로 68 을지병원 (하계동)',
    phone: '02-970-8000',
    cost: '96000',
    info: '인공 수정 시술, 체외 수정 시술',
    homepage: 'https://www.eulji.or.kr/index.jsp',
  },
  {
    name: '도곡함춘산부인과의원',
    description: '도곡함춘산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 강남구 논현로 142 동현빌딩 2~6층',
    phone: '02-1661-9722',
    cost: '50000',
    info: '인공 수정 시술',
    homepage: 'http://xn--399a1bw20a3ykt3dwvm.xn--3e0b707e/',
  },
  {
    name: '린여성병원',
    description: '린여성병원에 대한 설명란입니다.',
    address: '서울특별시 동대문구 답십리로 266 파워스빌딩 (장안동)',
    phone: '2244-1212',
    cost: '100000',
    info: '인공 수정 시술',
    homepage: 'https://linlady.com/',
  },
  {
    name: '메디아이여성병원',
    description: '메디아이여성병원에 대한 설명란입니다.',
    address: '서울특별시 노원구 노원로 448 메디아이여성병원 (상계동)',
    phone: '02-936-2122',
    cost: '70000',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'http://www.medi-i.com/',
  },
  {
    name: '미래아이산부인과의원',
    description: '미래아이산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 강서구 양천로 556 강서메디컬센터 1~7층',
    phone: '02-3665-2002',
    cost: '80000',
    info: '인공 수정 시술, 체외 수정 시술',
    homepage: 'http://i100.co.kr/',
  },
  {
    name: '미래연여성의원',
    description: '미래연여성의원에 대한 설명란입니다.',
    address: '서울특별시 송파구 올림픽로35다길 42 2층 202호 (신천동)',
    phone: '02-6012-2220',
    cost: '60000',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'https://www.miraeyeon.com:451/index.asp',
  },
  {
    name: '미래와희망산부인과의원',
    description: '미래와희망산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 강남구 언주로 707 지하1층~11층 (논현동)',
    phone: '02-3446-0011',
    cost: '52770',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'http://www.miraewa.com/',
  },
  {
    name: '미즈메디병원	',
    description: '미즈메디병원에 대한 설명란입니다.',
    address: '서울특별시 강서구 강서로 295 (내발산동)',
    phone: '02-2007-1000',
    cost: '58695',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'https://www.mizmedi.com/',
  },
  {
    name: '사랑아이여성의원',
    description: '사랑아이여성의원에 대한 설명란입니다.',
    address: '서울특별시 송파구 백제고분로 69, 애플타워 3층 (잠실동)',
    phone: '02-419-7501',
    cost: '60000',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'http://www.sarangi.co.kr/main/main.php?',
  },
  {
    name: '삼성미래여성병원',
    description: '삼성미래여성병원에 대한 설명란입니다.',
    address: '서울특별시 구로구 서해안로 2296 삼성미래여성병원 (오류동)',
    phone: '02-2682-2100',
    cost: '77000',
    info: '인공 수정 시술, 체외 수정 시술',
    homepage: 'http://www.samsungmirae.co.kr/',
  },
  {
    name: '삼성서울병원',
    description: '삼성서울병원에 대한 설명란입니다.',
    address: '서울특별시 강남구 일원로 81 (일원동, 삼성의료원)',
    phone: '02-3410-2114',
    cost: '76000',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'http://www.samsunghospital.com/home/main/index.do',
  },
  {
    name: '서울대학교병원',
    description: '서울대학교병원에 대한 설명란입니다.',
    address: '서울특별시 종로구 대학로 101 (연건동)',
    phone: '1588-5700',
    cost: '73000',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'https://www.snuh.org/main.do',
  },
  {
    name: '서울라헬여성의원',
    description: '서울라헬여성의원에 대한 설명란입니다.',
    address: '서울특별시 마포구 마포대로 109 롯데캐슬프레지던트 3층',
    phone: '02-3286-7500',
    cost: '46600',
    info: '인공 수정 시술, 체외 수정 시술',
    homepage: 'http://www.rachelivf.com/',
  },
  {
    name: '서울아가온여성의원',
    description: '서울아가온여성의원에 대한 설명란입니다.',
    address: '서울특별시 구로구 디지털로32길 79 조영빌딩 6, 8층 (구로동)',
    phone: '02-864-7500',
    cost: '62090',
    info: '인공 수정 시술, 체외 수정 시술',
    homepage: 'http://www.agaon.co.kr/',
  },
  {
    name: '서울아이앤여성의원',
    description: '서울아이앤여성의원에 대한 설명란입니다.',
    address: '서울특별시 강동구 천호대로 1053 이안 강동 컴홈스테이',
    phone: '02-6953-7119',
    cost: '-',
    info: '인공 수정 시술, 체외 수정 시술',
    homepage: 'http://www.in-fertilityclinic.com/index.do',
  },
  {
    name: '서울특별시보라매병원',
    description: '서울특별시보라매병원에 대한 설명란입니다.',
    address: '서울특별시 동작구 보라매로5길 20 (신대방동)',
    phone: '02-870-2114',
    cost: '47040',
    info: '인공 수정 시술',
    homepage: 'https://www.brmh.org/main/main.do',
  },
  {
    name: '서울특별시서울의료원',
    description: '서울특별시서울의료원에 대한 설명란입니다.',
    address: '서울특별시 중랑구 신내로 156 (신내동)',
    phone: '02-2276-7000',
    cost: '47980',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'https://www.seoulmc.or.kr/site/kr/index.jsp',
  },
  {
    name: '성심의료재단강동성심병원',
    description: '성심의료재단강동성심병원에 대한 설명란입니다.',
    address: '서울특별시 강동구 성안로 150 (길동)',
    phone: '02-2224-2114',
    cost: '106310',
    info: '인공 수정 시술',
    homepage: 'https://www.kdh.or.kr/',
  },
  {
    name: '성애의료재단 성애병원',
    description: '성애의료재단 성애병원에 대한 설명란입니다.',
    address: '서울특별시 영등포구 여의대방로53길 22 (신길동, 성애병원)',
    phone: '02-840-7114',
    cost: '52000',
    info: '인공 수정 시술',
    homepage: 'https://h.sungae.co.kr/index.do',
  },
  {
    name: '아란태산부인과의원',
    description: '아란태산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 영등포구 선유로 64 7층',
    phone: '02-2630-6600',
    cost: '60000',
    info: '인공 수정 시술',
    homepage: 'http://arante.co.kr/',
  },
  {
    name: '아이수산부인과의원',
    description: '아이수산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 서초구 동작대로 108, 303호 (방배동, 디오슈페리움2)',
    phone: '02-3483-2255',
    cost: '59000',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'http://aisu.co.kr/',
  },
  {
    name: '아이엘산부인과소아청소년과의원',
    description: '아이엘산부인과소아청소년과의원에 대한 설명란입니다.',
    address: '서울특별시 영등포구 양평로 32 지하 1~3층 (당산동6가)',
    phone: '02-2068-5111',
    cost: '90000',
    info: '인공 수정 시술',
    homepage: 'http://www.i-el.co.kr/',
  },
  {
    name: '에이치아이여성의원',
    description: '에이치아이여성의원에 대한 설명란입니다.',
    address: '서울특별시 강서구 강서로 463 새싹타워 2층 (마곡동)',
    phone: '02-3662-0401',
    cost: '52500',
    info: '인공 수정 시술, 체외 수정 시술',
    homepage: 'https://www.hifertility.co.kr/index.do',
  },
  {
    name: '에이치큐브병원',
    description: '에이치큐브병원에 대한 설명란입니다.',
    address: '서울특별시 도봉구 도봉로 604 (창동)',
    phone: '02-900-2000',
    cost: '70000',
    info: '인공 수정 시술, 체외 수정 시술',
    homepage: 'http://www.hcube.kr/',
  },
  {
    name: '엠여성의원',
    description: '엠여성의원에 대한 설명란입니다.',
    address: '서울특별시 강남구 테헤란로 407',
    phone: '02-6188-0070',
    cost: '70000',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'http://www.mfertility.com/2014/index.php',
  },
  {
    name: '엠제이산부인과의원',
    description: '엠제이산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 금천구 두산로 81 지하1층, 2~8층 (독산동)',
    phone: '2109-3000',
    cost: '100000',
    info: '인공 수정 시술',
    homepage: 'http://www.mjobgy.com/',
  },
  {
    name: '연세대학교의과대학 강남세브란스병원',
    description: '연세대학교의과대학 강남세브란스병원에 대한 설명란입니다.',
    address: '서울특별시 강남구 언주로 211 강남세브란스병원 (도곡동)',
    phone: '02-2019-3114',
    cost: '47980',
    info: '인공 수정 시술',
    homepage: 'https://gs.severance.healthcare/gs/index.do',
  },
  {
    name: '연세대학교의과대학세브란스병원',
    description: '연세대학교의과대학세브란스병원에 대한 설명란입니다.',
    address: '서울특별시 서대문구 연세로 50-1 (신촌동)',
    phone: '02-2228-0114',
    cost: '-',
    info: '인공 수정 시술, 체외 수정 시술',
    homepage: 'https://sev.severance.healthcare/sev/index.do',
  },
  {
    name: '연세더블유산부인과의원',
    description: '연세더블유산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 서초구 반포대로 111 보광빌딩 4~5층 (서초동)',
    phone: '02-587-2300',
    cost: '50000',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'http://www.yswivf.com/',
  },
  //   {
  //     name: "연세더블유산부인과",
  //     address: "서울특별시 마포구 양화로 48 강서정형외과 1층 (합정동)",
  //     phone: "02-334-2330",
  //     cost: "50000",
  //     info: "인공 수정 시술",
  //     // 홈페이지 다시 찾아보기

  //   }, // 현재 페업한 병원
  {
    name: '연세수피아산부인과의원',
    description: '연세수피아산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 송파구 위례서로 248 세계로병원 3층 301,302호',
    phone: '02-408-8275',
    cost: '80000',
    info: '인공 수정 시술',
    homepage: 'https://supiaclinic.modoo.at/',
  },
  {
    name: '우리기쁜산부인과의원',
    description: '우리기쁜산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 성북구 종암로 147 지상 1~8층 (종암동)',
    phone: '02-2039-1000',
    cost: '60000',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'http://wejoyful.com/index.asp',
  },
  {
    name: '유광사여성병원',
    description: '유광사여성병원에 대한 설명란입니다.',
    address: '서울특별시 강서구 강서로 194 (화곡동)',
    phone: '02-2608-1011',
    cost: '60000',
    info: '인공 수정 시술, 체외 수정 시술',
    homepage: 'http://www.yookwangsa.co.kr/',
  },
  {
    name: '윤호병원',
    description: '윤호병원에 대한 설명란입니다.',
    address: '서울특별시 강남구 압구정로 304 지하 1~2층, 1~4층, 7층 (신사동, 윤호병원)',
    phone: '02-512-0500',
    cost: '50000',
    info: '인공 수정 시술',
    homepage: 'http://yoonhohospital.co.kr/',
  },
  {
    name: '은산부인과의원',
    description: '은산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 은평구 연서로 137 4층 (구산동)',
    phone: '02-359-7175',
    cost: '90000',
    info: '인공 수정 시술',
    homepage: 'http://www.eunobgy.co.kr/',
  },
  {
    name: '은혜산부인과의원',
    description: '은혜산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 은평구 진흥로 133 D동 B1~2층, 2~4층 (대조동)',
    phone: '02-353-4307',
    cost: '47000',
    info: '인공 수정 시술',
    homepage: 'http://www.eunhaelove.com/',
  },
  {
    name: '의료법인마리아의료재단마리아병원	',
    description: '의료법인마리아의료재단마리아병원에 대한 설명란입니다.',
    address: '서울특별시 동대문구 천호대로 20 (신설동)',
    phone: '02-2234-6555',
    cost: '40000~75000',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'https://www.mariababy.com/',
  },
  {
    name: '의료법인마리아의료재단마리아병원	',
    description: '의료법인마리아의료재단마리아병원에 대한 설명란입니다.',
    address: '서울특별시 송파구 송이로 152 마리아 의료재단 새병원',
    phone: '02-2152-6555',
    cost: '40000~75000',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'https://www.mariababy.com/branch/branch_intro.asp?code1=2',
  },
  {
    name: '의료법인마리아의료재단마리아의원',
    description: '의료법인마리아의료재단마리아병원에 대한 설명란입니다.',
    address: '서울특별시 중랑구 망우로 267 (상봉동)',
    phone: '02-2218-7555',
    cost: '40000~75000',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'https://www.mariababy.com/branch/branch_intro.asp?code1=12',
  },
  {
    name: '이화여자대학교의과대학부속목동병원',
    description: '이화여자대학교의과대학부속목동병원에 대한 설명란입니다.',
    address: '서울특별시 양천구 안양천로 1071 (목동)',
    phone: '02-2650-5114',
    cost: '122700~141100',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'https://mokdong.eumc.ac.kr/main.do',
  },
  {
    name: '인정병원',
    description: '인정병원에 대한 설명란입니다.',
    address: '서울특별시 은평구 응암로 164 (응암동)',
    phone: '02-309-0909',
    cost: '55000',
    info: '인공 수정 시술, 체외 수정 시술',
    homepage: 'https://injunghp.co.kr/main/main.php',
  },
  {
    name: '장스여성병원',
    description: '장스여성병원에 대한 설명란입니다.',
    address: '서울특별시 중랑구 용마산로117길 49 장스여성병원 비동 (7층)',
    phone: '02-490-4000',
    cost: '50000',
    info: '인공 수정 시술, 체외 수정 시술',
    homepage: 'http://jangshospital.co.kr/default/',
  },
  {
    name: '재단법인아산사회복지재단 서울아산병원',
    description: '재단법인아산사회복지재단 서울아산병원에 대한 설명란입니다.',
    address: '서울특별시 송파구 올림픽로43길 88 서울아산병원 (풍납동)',
    phone: '02-3010-3114',
    cost: '80000',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'https://www.asanfoundation.or.kr/af/main.do',
  },
  {
    name: '조윤희산부인과의원',
    description: '조윤희산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 금천구 시흥대로 212 2층 (시흥동)',
    phone: '02-802-8892',
    cost: '-',
    info: '인공 수정 시술',
    homepage: 'http://xn--vb0b562a6lc1rjcma11ci01d.kr/',
  },
  {
    name: '차의과학대학교 강남차병원',
    description: '차의과학대학교 강남차병원에 대한 설명란입니다.',
    address: '서울특별시 강남구 논현로 566 강남차병원 (역삼동650-9, 606-4, 605외2필지(지하7층~지하1층)',
    phone: '02-3468-3000',
    cost: '106314',
    info: '인공 수정 시술, 체외 수정 시술, 난자 냉동 시술',
    homepage: 'https://gangnam.chamc.co.kr/Default.cha',
  },
  {
    name: '청담마리산부인과의원',
    description: '청담마리산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 강남구 삼성로 712 (청담동)',
    phone: '02-2156-9200',
    cost: '73000',
    info: '인공 수정 시술',
    homepage: 'http://marieclinic.co.kr/',
  },
  {
    name: '청화병원',
    description: '청화병원에 대한 설명란입니다.',
    address: '서울특별시 동작구 장승배기로 108 (노량진동)',
    phone: '02-815-3788',
    cost: '70000',
    info: '인공 수정 시술',
    homepage: 'http://www.cheongwha.com/',
  },
  {
    name: '퀸스메디산부인과의원',
    description: '퀸스메디산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 노원구 동일로 1059 (공릉동)',
    phone: '02-948-7588',
    cost: '51260',
    info: '인공 수정 시술',
    homepage: 'http://www.queensmedi.co.kr/',
  },
  {
    name: '포미즈여성병원',
    description: '포미즈여성병원에 대한 설명란입니다.',
    address: '서울특별시 양천구 공항대로 610 (목동, 정종일산부인과)',
    phone: '02-2651-7500',
    cost: '80000',
    info: '인공 수정 시술',
    homepage: 'http://www.iformiz.co.kr/',
  },
  {
    name: '포유문산부인과의원',
    description: '포유문산부인과의원에 대한 설명란입니다.',
    address: '서울특별시 송파구 양재대로60길 3(가락동)',
    phone: '02-443-1600',
    cost: '-',
    info: '인공 수정 시술',
    homepage: 'http://www.moonob.co.kr/',
  },
  {
    name: '학교법인 고려중앙학원 고려대학교의과대학부속병원(안암병원)',
    description: '학교법인 고려중앙학원 고려대학교의과대학부속병원(안암병원)에 대한 설명란입니다.',
    address: '서울특별시 성북구 고려대로 73 고려대병원 (안암동5가)',
    phone: '1577-0083',
    cost: '91730',
    info: '인공 수정 시술, 체외 수정 시술',
    homepage: 'http://anam.kumc.or.kr/main/index.do',
  },
  {
    name: '함춘여성의원	',
    description: '함춘여성의원에 대한 설명란입니다.',
    address: '서울특별시 서초구 서초중앙로8길 10 지하~5층 (서초동)',
    phone: '02-522-0123',
    cost: '91000',
    info: '인공 수정 시술, 체외 수정 시술',
    homepage: 'http://www.hamchoon.co.kr/',
  },
  {
    name: '햇빛병원',
    description: '햇빛병원에 대한 설명란입니다.',
    address: '서울특별시 강북구 도봉로 74 (미아동)',
    phone: '02-983-7771',
    cost: '70000',
    info: '인공 수정 시술',
    homepage: 'http://www.hatvit.co.kr/',
  },
  {
    name: '호산여성병원	',
    description: '호산여성병원에 대한 설명란입니다.',
    address: '서울특별시 강남구 언주로 871 (신사동, 호산병원)',
    phone: '02-546-3493',
    cost: '60000',
    info: '인공 수정 시술',
    homepage: 'http://ladyhosan.co.kr/',
  },
];
