name: Node.js CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Docker Login
        run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
      - name: Docker Build
        env:
          PLATFORM: linux/amd64
          REPO: hola_server
        run: |
          docker build --platform $PLATFORM -t $REPO .
          docker tag $REPO ${{ secrets.USERNAME }}/${REPO}:${GITHUB_SHA::7}
          docker push ${{ secrets.USERNAME }}/${REPO}:${GITHUB_SHA::7}
      - name: Docker Pull & Run From Hub
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.PORT}}
          timeout: 40s
          envs: GITHUB_SHA
          script: |
            docker login
            docker pull ${{secrets.USERNAME}}/${REPO}
            docker stop $REPO
            docker rm $REPO
